### PR TITLE
Task System Initialization

### PR DESCRIPTION
**Pull request by CyFeng16**
Initialization of task system, includes a markdown file and a PDF format mind-mapping.

### CODE REVIEW

**Comment by huan** [comment]
Hi @CyFeng16, 

Thank you very much for taking the responsibilities of the Task System!

This PR is good, however, it needs to be changed to follow the following rules to make the repository clear and simply:

1. Keep lowercase for all the filename & directory names(Do not use any UPPERCASE, i.e. `TaskSystem` -> `task-system`), and to be consistent, we should always use `-` instead of `_` in the filename(exactly as in your PR)
1. Use markdown text to describe diagrams when possible. Please do not use PDF or PNG when we can describe it as an outline, which is the most cases.

Please let me know when you finish the changes, thanks.

**Comment by CyFeng16** [comment]
Well, my apology.
I will follow the rules and reopen a new pull request. Thx.

**Comment by huan** [comment]
@CyFeng16 no problem, just suggestions and we will follow the simple rules in the future.

BTW: You can update your PR (branch from your cloned repo), instead of closed it. I'd like to suggest that you keep this PR to be open and update it, you will see how it works then. :)

**Comment by CyFeng16** [comment]
Sure, I will try!
The mind-mapping loses its resolution when it was added into markdown file.
I'd like to try again.

**Comment by CyFeng16** [comment]
I just put the a-bit-low-resolution 'png' format picture in the README.md and leave it alone.
Now the pull request is ready to double check, extremely grateful.

**Comment by huan** [comment]
No, please do not put png files in the readme.

Instead, I'd like to suggest you just put plain text in the readme, to make it simple and clear.

Please just put text in readme this time, and if you have any question, let's discuss it in person next time.

**Comment by CyFeng16** [comment]
Well, I write a markdown in text about the mind map.

**Comment by huan** [comment]
Thanks!

**Pull request merged**
